use serde::{Deserialize, Serialize};

/// Global collection stats rquired by BM25 scoring
/// This will be written to data/index/collection_stats.json
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct CollectionStats {
    pub total_docs: u64,
    pub total_tokens: u64,
    pub avg_doc_len: f64,
}

/// Metadate for a single indexed passage
/// This will be wrtitten to data/index/doc_table.csv
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct DocMeta {
    pub doc_id: u32,
    pub external_id: u32,
    pub doc_len: u32,
}

/// Intermediate posting generated by the parser
/// This will be written data/runs/run_xxx.tsv
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord)]
pub struct Posting {
    pub term: String,
    pub doc_id: u32,
    pub freq: u32,
}
